In [5]:
%load_ext autoreload
%autoreload 2

import os
import sys
import numpy as np
from MM_Util.mol import *

# Reading amol object from a path
mol = Mol("sample_data")
mol.gaussian()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
# Obtaining mol object Atrributes
print(mol.xyz)
print(mol.atoms)
print(mol.Vibs)
print(mol.Freq)
print(mol.E)
print(mol.H)
print(mol.E)

[[-0.941237 -0.20418   0.      ]
 [ 0.019994 -0.166948 -0.      ]
 [-1.227006  0.714344  0.      ]]
['O', 'H', 'H']
[[[-0.   -0.   -0.07]
  [ 0.    0.43  0.56]
  [ 0.   -0.43  0.56]]

 [[ 0.   -0.    0.05]
  [ 0.    0.59 -0.39]
  [-0.   -0.59 -0.39]]]
[1602.4365 3818.8124 3923.9167]
-76.4585319615
-76.433462
-76.4585319615
